version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
  
  #  mongo:
  #    image: mongo
  #    restart: always
  #    ports:
  #      - 27017:27017
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: rootroot
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    #    depends_on:
    #      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:FreyaFlexForm_2564@host.docker.internal:27017/